name: Resolve pnpm version

description: Extract pnpm version from a package.json's packageManager field

inputs:
  package_json:
    description: Path to package.json to read
    required: true
    default: ./package.json

outputs:
  version:
    description: Resolved pnpm version (semver)
    value: ${{ steps.read.outputs.pnpm_version }}

runs:
  using: composite
  steps:
    - id: read
      shell: bash
      run: |
        if ! command -v jq >/dev/null 2>&1; then
          echo "jq is required" >&2
          exit 1
        fi
        file="${{ inputs.package_json }}"
        if [ ! -f "$file" ]; then
          echo "package.json not found at $file" >&2
          exit 1
        fi
        raw=$(jq -r '.packageManager // empty' "$file")
        if [ -z "$raw" ]; then
          echo "packageManager not found in $file" >&2
          exit 1
        fi
        ver=$(printf '%s' "$raw" | sed -E 's/^pnpm@([^+]+).*$/\1/')
        if [ -z "$ver" ]; then
          echo "Failed to parse pnpm version from: $raw" >&2
          exit 1
        fi
        echo "pnpm_version=$ver" >> "$GITHUB_OUTPUT"
