[workspace]
resolver = "3"
members = ["crates/*"]
exclude = ["crates/rustowl/algo-tests", "crates/rustowl/perf-tests/dummy-package"]
default-members = ["crates/rustowl"]

[workspace.package]
version = "0.4.0"
edition = "2024"
documentation = "https://github.com/cordx56/rustowl/blob/main/README.md"
readme = "README.md"
repository = "https://github.com/cordx56/rustowl"
license = "MPL-2.0"

[workspace.dependencies]
anstyle = "1"
cargo_metadata = "0.23"
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
clap_complete_nushell = "4"
clap_mangen = "0.3"
clap-verbosity-flag = { version = "3", default-features = false, features = [
  "tracing",
] }
criterion = { version = "0.8", features = ["html_reports"] }
flate2 = "1"
indexmap = "2.14.0"
indicatif = "0.18"
insta = "1.47"
process_alive = "0.2"
rayon = "1"
regex = "1"
reqwest = { version = "0.13.4", features = ["socks"] }
rustversion = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tar = "0.4.46"
tempfile = "3"
tikv-jemalloc-sys = { version = "0.7", features = ["override_allocator_on_supported_platforms"] }
tokio = { version = "1", features = [
  "fs",
  "io-std",
  "io-util",
  "macros",
  "process",
  "rt",
  "rt-multi-thread",
  "sync",
  "time",
] }
tokio-util = "0.7"
tower-lsp = "0.20"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tree-sitter-highlight = "0.27"
tree-sitter-rust = "0.24"
uuid = { version = "1", features = ["v4"] }
zip = "8.6.0"

[workspace.lints.rust]
absolute_paths_not_starting_with_crate = "warn"
non_ascii_idents = "warn"
tail_expr_drop_order = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(coverage)", "cfg(coverage_nightly)"] }
unit_bindings = "warn"
unsafe_op_in_unsafe_fn = "warn"
unused_unsafe = "warn"

[profile.release]
opt-level = 3
strip = "debuginfo"
lto = "fat"
codegen-units = 1

[profile.release.package."*"]
opt-level = 3
strip = "symbols"

[profile.security]
inherits = "release"
opt-level = 1
debug = true
strip = "none"
debug-assertions = true
overflow-checks = true

[profile.windows-release]
inherits = "release"
lto = "off"
