;; -*- mode: eask; lexical-binding: t -*-

(package "rustowl"
         "0.3.4"
         "Visualize Ownership and Lifetimes in Rust")

(website-url "https://github.com/cordx56/rustowl")
(keywords "lifetime" "ownership" "rust" "visualization" "tools")

(package-file "emacs/rustowl.el")

(script "test" "eask test ert emacs/eask-test.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "26.4")
(depends-on "lsp-mode" "9.0.0")
