;;; cc-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from rustowl.el

(eval-after-load 'lsp-mode '(lsp-register-client (make-lsp-client :new-connection (lsp-stdio-connection '("rustowl")) :major-modes '(rust-mode) :server-id 'rustowl :priority -1 :add-on? t)))
(defvar rustowl-cursor-timer nil)
(defvar rustowl-cursor-timeout 2)
(autoload 'rustowl-reset-cursor-timer "rustowl")
(autoload 'rustowl-enable-cursor "rustowl")
(autoload 'rustowl-disable-cursor "rustowl")
(register-definition-prefixes "rustowl" '("rustowl-"))

;;; End of scraped data

(provide 'cc-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cc-autoloads.el ends here
