name: "Rust toolchain (from rust-toolchain.toml)"
description: "Installs yq, reads rust-toolchain.toml, and installs that Rust toolchain via dtolnay/rust-toolchain."
inputs:
  targets:
    description: "Comma-separated Rust target triples to install"
    required: false
    default: ""
  components:
    description: "Comma-separated Rust components to install"
    required: false
    default: ""
outputs:
  toolchain:
    description: "Resolved toolchain channel"
    value: ${{ steps.get_toolchain.outputs.toolchain }}
runs:
  using: "composite"
  steps:
    - name: Install yq (mikefarah)
      shell: bash
      run: |
        set -euo pipefail

        version="v4.50.1"

        os="${RUNNER_OS}"     # Linux|macOS|Windows
        arch="${RUNNER_ARCH}" # X64|ARM64

        case "${os}" in
          Linux) platform="linux"; ext="" ;;
          macOS) platform="darwin"; ext="" ;;
          Windows) platform="windows"; ext=".exe" ;;
          *) echo "Unsupported runner OS: ${os}" >&2; exit 1 ;;
        esac

        case "${arch}" in
          X64) cpu="amd64" ;;
          ARM64) cpu="arm64" ;;
          *) echo "Unsupported runner arch: ${arch}" >&2; exit 1 ;;
        esac

        url="https://github.com/mikefarah/yq/releases/download/${version}/yq_${platform}_${cpu}${ext}"

        install_dir="${RUNNER_TEMP}/yq"
        mkdir -p "${install_dir}"
        bin="${install_dir}/yq${ext}"

        echo "Downloading ${url}" >&2

        if [[ "${os}" == "Windows" ]]; then
          powershell -NoProfile -Command "Invoke-WebRequest -Uri '${url}' -OutFile '${bin}'"
        else
          curl -fsSL "${url}" -o "${bin}"
        fi

        if [[ "${os}" != "Windows" ]]; then
          chmod +x "${bin}"
        fi

        echo "${install_dir}" >> "${GITHUB_PATH}"

        "${bin}" --version
    - name: Get toolchain from rust-toolchain.toml
      id: get_toolchain
      shell: bash
      run: |
        ext=""
        if [[ "${RUNNER_OS}" == "Windows" ]]; then
          ext=".exe"
        fi
        toolchain="$(${RUNNER_TEMP}/yq/yq${ext} -r '.toolchain.channel' rust-toolchain.toml)"
        if [[ -z "${toolchain}" || "${toolchain}" == "null" ]]; then
          echo "Could not determine toolchain from rust-toolchain.toml" >&2
          exit 1
        fi
        echo "toolchain=${toolchain}" >> "${GITHUB_OUTPUT}"
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
      with:
        toolchain: ${{ steps.get_toolchain.outputs.toolchain }}
        targets: ${{ inputs.targets }}
        components: ${{ inputs.components }}
