name: setup-rust-llvm
description: >
  Install LLVM/Clang matching Rust's LLVM version with forward-patch fallback.
  Designed for cross-language LTO correctness.

outputs:
  llvm-version:
    description: LLVM version selected
    value: ${{ steps.export.outputs.llvm_version }}

runs:
  using: composite
  steps:
    # ------------------------------------------------------------
    # Detect Rust LLVM version
    # ------------------------------------------------------------
    - name: Detect Rust LLVM version
      id: detect
      shell: bash
      run: |
        set -euo pipefail

        LLVM_FULL=$(rustc -vV | sed -n 's/^LLVM version: //p')
        LLVM_MAJOR=$(echo "$LLVM_FULL" | cut -d. -f1)
        LLVM_MINOR=$(echo "$LLVM_FULL" | cut -d. -f2)
        LLVM_PATCH=$(echo "$LLVM_FULL" | cut -d. -f3)

        echo "LLVM_FULL=$LLVM_FULL"   >> "$GITHUB_ENV"
        echo "LLVM_MAJOR=$LLVM_MAJOR" >> "$GITHUB_ENV"
        echo "LLVM_MINOR=$LLVM_MINOR" >> "$GITHUB_ENV"
        echo "LLVM_PATCH=$LLVM_PATCH" >> "$GITHUB_ENV"

    # ------------------------------------------------------------
    # Fetch all available patches for this major.minor
    # ------------------------------------------------------------
    - name: Fetch LLVM patch candidates
      id: patches
      shell: bash
      run: |
        set -euo pipefail

        curl -fsSL https://api.github.com/repos/llvm/llvm-project/tags \
          | jq -r '.[].name' \
          | sed 's/^llvmorg-//' \
          | grep "^${LLVM_MAJOR}\.${LLVM_MINOR}\." \
          | sort -V \
          > llvm_patches.txt

        if [[ ! -s llvm_patches.txt ]]; then
          echo "::error::No LLVM releases found for ${LLVM_MAJOR}.${LLVM_MINOR}"
          exit 1
        fi

    # ------------------------------------------------------------
    # Try patches >= Rust patch, in ascending order
    # ------------------------------------------------------------
    - name: Probe LLVM versions
      id: probe
      shell: bash
      run: |
        set -euo pipefail

        SELECTED=""

        while read -r VER; do
          PATCH=$(echo "$VER" | cut -d. -f3)

          if (( PATCH < LLVM_PATCH )); then
            continue
          fi

          echo "::group::Trying LLVM $VER"
          if llvm_ver="$VER" \
             && echo "LLVM_TRY=$VER" >> "$GITHUB_ENV"; then
            echo "::endgroup::"
            SELECTED="$VER"
            break
          fi
          echo "::endgroup::"
        done < llvm_patches.txt

        if [[ -z "$SELECTED" ]]; then
          echo "::error::No usable LLVM binary found for ${LLVM_MAJOR}.${LLVM_MINOR}.x"
          exit 1
        fi

        echo "LLVM_SELECTED=$SELECTED" >> "$GITHUB_ENV"

    # ------------------------------------------------------------
    # Install selected LLVM
    # ------------------------------------------------------------
    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: ${{ env.LLVM_SELECTED }}
        env: true

    # ------------------------------------------------------------
    # Verify LLVM compatibility
    # ------------------------------------------------------------
    - name: Verify LLVM compatibility
      shell: bash
      run: |
        set -euo pipefail

        RUST_LLVM=$(rustc -vV | sed -n 's/^LLVM version: //p')
        CLANG_LLVM=$(clang --version | sed -n 's/.*LLVM version \([0-9.]*\).*/\1/p')

        echo "Rust LLVM  : $RUST_LLVM"
        echo "Clang LLVM : $CLANG_LLVM"

        if [[ "$CLANG_LLVM" != "$LLVM_SELECTED" ]]; then
          echo "::warning::Installed LLVM does not match selected version"
        fi

    # ------------------------------------------------------------
    # Export outputs
    # ------------------------------------------------------------
    - name: Export outputs
      id: export
      shell: bash
      run: |
        echo "llvm_version=${LLVM_SELECTED}" >> "$GITHUB_OUTPUT"

