name: Emacs Plugin CI

on:
  push:
    paths:
      - Eask
      - rustowl.el
      - emacs-tests/**
      - .github/workflows/emacs-checks.yml
    branches:
      - main
  pull_request:
    paths:
      - Eask
      - rustowl.el
      - emacs-tests/**
      - .github/workflows/emacs-checks.yml

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Emacs
        uses: purcell/setup-emacs@bdc64dc730ae1fcba200bfd52cb1b4cf6159cbe5 # v8.0
        with:
          version: 31.1

      - name: Set up Eask
        uses: emacs-eask/setup-eask@098ca9e1d90c188dbfee5c91688fbbaa930499b6 # v3
        with:
          version: 0.12.9

      - name: Setup Rustowl
        run: |
          ./scripts/toolchain cargo build --release
          ./scripts/toolchain cargo install --path crates/rustowl --locked

      - name: Lint Regexps
        run: eask lint regexps

      - name: Lint Package
        run: eask lint package

      - name: Lint License
        run: eask lint license

      - name: Lint Keywords
        run: eask lint keywords

      - name: Lint Indent
        run: eask lint indent

      - name: Lint Checkdocs
        run: eask lint checkdoc

      - name: Lint Declare
        run: eask lint declare

      - name: Lint elisp-lint
        run: eask lint elisp-lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Emacs
        uses: purcell/setup-emacs@bdc64dc730ae1fcba200bfd52cb1b4cf6159cbe5 # v8.0
        with:
          version: 31.1

      - name: Set up Eask
        uses: emacs-eask/setup-eask@098ca9e1d90c188dbfee5c91688fbbaa930499b6 # v3
        with:
          version: 0.12.9

      - name: Setup Rustowl
        run: |
          ./scripts/toolchain cargo build --release
          ./scripts/toolchain cargo install --path . --locked

      - name: Run Tests
        run: |
          eask install-deps
          eask run script test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Emacs
        uses: purcell/setup-emacs@bdc64dc730ae1fcba200bfd52cb1b4cf6159cbe5 # v8.0
        with:
          version: 31.1

      - name: Setup Rustowl
        run: |
          ./scripts/toolchain cargo build --release
          ./scripts/toolchain cargo install --path . --locked

      - name: Setup Eask
        uses: emacs-eask/setup-eask@098ca9e1d90c188dbfee5c91688fbbaa930499b6 # v3
        with:
          version: 0.12.9

      - name: Build And Compile
        run: |
          eask package
          eask install
          eask compile
